
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

from tkinter import *
import importlib.util
modulepath = OUTPUT_PATH + "../backend/mainModu"
print("OUTPUT PATH :", OUTPUT_PATH)
spec = importlib.util.spec_from_file_location("mainModule", "../backend/mainModule.py")
foo = importlib.util.module_from_spec(spec)
spec.loader.exec_module(foo)
# foo.MyClass()

# from ..backend import mainModule
# scanner = importlib.import_module(name, package)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def invoke_scanner():
    foo.main()


window = Tk()

window.geometry("720x480")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 480,
    width = 720,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    32.0,
    23.0,
    692.0,
    389.0,
    fill="#D5EBF4",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: invoke_scanner(),
    relief="flat"
)
button_1.place(
    x=235.0,
    y=401.0,
    width=250.0,
    height=65.0
)
window.resizable(False, False)
window.mainloop()